name: Rotate customer app registration keys

on: 
  workflow_dispatch:

env:
  AZURE_CREDENTIALS: >
    {
      "clientId": "${{ secrets.ARM_CLIENT_ID }}",
      "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}",
      "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}",
      "tenantId": "${{ secrets.ARM_TENANT_ID }}"
    }
  
jobs: 
  get-tfstate-files:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}

    - name: Azure CLI collect terraform state files
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az storage blob list -c tfstate-customeronboarding --account-name sacustomeronboarding0000 --query "[].name" -o json > $GITHUB_WORKSPACE/tfstatefiles.json
    
    - name: Import terraform state files to output
      id: set-matrix
      run: |
        JSON=$(cat $GITHUB_WORKSPACE/tfstatefiles.json)
        echo "::set-output name=matrix::${JSON//'%'/'%25'}"
        echo "Test ${JSON//'%'/'%25'}"
        
  set-matrix:
    needs: get-tfstate-files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # tfstate_file: ${{fromJson(needs.get-tfstate-files.outputs.matrix)}}
        tfstate_file: [test01.onmicrosoft.com,test02.onmicrosoft.com]
    
    steps:
    - name: Display matrix
      run: echo ${{matrix.tfstate_file}}
