name: Rotate customer app registration keys

on: 
  workflow_dispatch:

env:
  AZURE_CREDENTIALS: >
    {
      "clientId": "${{ secrets.ARM_CLIENT_ID }}",
      "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}",
      "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}",
      "tenantId": "${{ secrets.ARM_TENANT_ID }}"
    }
  
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}

    - name: Azure CLI collect terraform state files
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az storage blob list -c tfstate-customeronboarding --account-name sacustomeronboarding0000 --query "[].name" -o json > $GITHUB_WORKSPACE/tfstatefiles.json
    
    - name: Import terraform state files to output
      id: import_json
      run: |
        content='cat $GITHUB_WORKSPACE/tfstatefiles.json'
        test="Test"
        echo "::set-output name=packageJson::$content"
        echo "::set-output name=test::$test"
        echo "${{ steps.import_json.outputs.packageJson }}"
        echo "${{ steps.import_json.outputs.test }}"
        echo ${{ test}}
        echo ${{ content }}
      # run: |
      #   echo "${{fromJson(steps.import_json.outputs.packageJson)}}"