name: Rotate customer app registration keys

on: 
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
jobs: 
  collect-terraform-state-files:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: 'Run az commands'
        run: |
          az account show
          az group list
          pwd 