name: Rotate Primary App Secret

on:
  workflow_dispatch:

permissions:
      id-token: write

jobs:

  rotate-primary-secret:

    runs-on: ubuntu-latest
    outputs: 
      primarykey: ${{ steps.rotate-secret.outputs.primarykey }}
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: 'Run command to rotate secret'
        id: rotate-secret
        run: |
          primarykey=$(az ad app credential reset --id dc25f18c-c657-4c3e-8fcc-ddfa36703f25 --credential-description "PrimaryKey" --query password)

      - name: 'Update GitHub Org Secret'
        run: |
          gh secret set Test --body ${{ steps.rotate-secret.outputs.primarykey }} --repo kevinbasoftcat/terraform-deployments
