name: Rotate Primary App Secret

on:
  workflow_dispatch:

permissions:
      id-token: write

jobs:

  rotate-primary-secret:

    runs-on: ubuntu-latest

    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: 'Run az commands to rotate secret'
        run: |
          az ad app credential list --id cbd73d1c-f779-4d82-8ff4-86a67b87acdd

      - name: 'Run powershell to rotate secret'
          uses: azure/powershell@v1
          with:
             inlineScript: |
               Get-AzADApplication
             azPSVersion: "latest"