name: Terraform Apply

on: 
  workflow_dispatch:
    inputs:
      customertenantid:
        description: 'Please provide the customer Azure AD Tenant ID'
        required: true
        type: string
defaults:
  run:
    working-directory: ./Azure-Managed-Service-Customer-Onboarding

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init -backend-config=resource_group_name=AzureMigrations -backend-config=storage_account_name=customerterraformstate -backend-config=container_name=customer-onboarding-state -backend-config=key=tfstate-${{ github.event.inputs.customertenantid }}.tfstate -backend-config=arm_subscription_id=${{secrets.ARM_SUBSCRIPTION_ID}} -backend-config=arm_tenant_id=${{secrets.ARM_TENANT_ID}} -backend-config=arm_client_id=${{secrets.ARM_CLIENT_ID}} -backend-config=arm_client_secret=${{secrets.ARM_CLIENT_SECRET}}

      #- name: Terraform Validate
      #  run: terraform validate

      #- name: Terraform Plan
      #  run: terraform plan -var customer_tenant_id=${{ github.event.inputs.customertenantid }}
        
      #- name: Terraform Apply
      #  run: terraform apply -var customer_tenant_id=${{ github.event.inputs.customertenantid }}
