name: Managed Azure Customer Tenant Onboarding

on: 
  workflow_dispatch:
    inputs:
      customertenantid:
        description: 'Please provide the customer Azure AD tenant initial default domain. This will be the unique onmicrosoft.com domain name'
        required: true
        type: string
defaults:
  run:
    working-directory: ./Azure-Managed-Service-Customer-Onboarding

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Azure-Managed-Service-Customer-Onboarding

    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init -backend-config=storage_account_name=${{secrets.STORAGE_ACCOUNT}} -backend-config=key=${{ github.event.inputs.customertenantid }}.tfstate

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var customer_tenant_id=${{ github.event.inputs.customertenantid }}
        
      - name: Terraform Apply
        run: terraform apply -var customer_tenant_id=${{ github.event.inputs.customertenantid }} --auto-approve

  create_file:
    runs-on: ubuntu-latest
    needs: terraform
      
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Create customer information file
        run: |
          echo -n -e "${{ github.event.inputs.customertenantid }}" > ${{ github.event.inputs.customertenantid }}.txt

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: commit
        run: |
          git add ${{ github.event.inputs.customertenantid }}.txt
          git commit -m "Customer onboarded commit"
          git push origin main