name: Managed Azure Customer Tenant Onboarding

on: 
  workflow_dispatch:
    inputs:
      customertenantid:
        description: 'Please provide the customer Azure AD tenant initial default domain. This will be the unique onmicrosoft.com domain name'
        required: true
        type: string
defaults:
  run:
    working-directory: ./Azure-Managed-Service-Customer-Onboarding

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      # - name: Terraform Init
      #   run: terraform init -backend-config=storage_account_name=${{secrets.STORAGE_ACCOUNT}} -backend-config=key=${{ github.event.inputs.customertenantid }}.tfstate

      # - name: Terraform Validate
      #   run: terraform validate

      # - name: Terraform Plan
      #   run: terraform plan -var customer_tenant_id=${{ github.event.inputs.customertenantid }}
        
      # - name: Terraform Apply
      #   run: terraform apply -var customer_tenant_id=${{ github.event.inputs.customertenantid }} --auto-approve

  write-version:
    runs-on: ubuntu-latest
    name: Write customer tenant and keyvault to file
    
    steps:
      - name: Create file
        uses: "finnp/create-file-action@master"
            env:
              FILE_NAME: "customer_information/${{ github.event.inputs.customertenantid }}.txt"