name: Managed Azure Customer Tenant Onboarding

on: 
  workflow_dispatch:
    inputs:
      customertenantid:
        description: 'Please provide the customer Azure AD tenant initial default domain. This will be the unique onmicrosoft.com domain name'
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Azure-Managed-Service-Customer-Onboarding

    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init -backend-config=storage_account_name=${{secrets.STORAGE_ACCOUNT}} -backend-config=key=${{ github.event.inputs.customertenantid }}.tfstate

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var customer_tenant_id=${{ github.event.inputs.customertenantid }}
        
      - name: Terraform Apply
        run: terraform apply -var customer_tenant_id=${{ github.event.inputs.customertenantid }} --auto-approve

  create_file:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Customer-Information
    needs: terraform
      
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set current date as a variable
        run: currentDate='date'

      - name: Get terraform output for key vault name
        run: keyvault_name=$(terraform output keyvault_name)

      - name: Create customer information file
        run: |
          echo "Customer Repo Information"                    > ${{ github.event.inputs.customertenantid }}-$keyvault_name.txt
          echo "${{ github.event.inputs.customertenantid }}" >> ${{ github.event.inputs.customertenantid }}-$keyvault_name.txt
          echo $currentDate                                 >>> ${{ github.event.inputs.customertenantid }}-$keyvault_name.txt

      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Add customer file to repository
        run: |
          git add ${{ github.event.inputs.customertenantid }}-$keyvault_name.txt
          git commit -m "Customer onboarded commit"
          git push origin main