name: Terraform Apply

on: 
  workflow_dispatch:
    inputs:
      CustomerTenantID:
        description: 'Please provide the customer Azure AD Tenant ID'
        required: true
defaults:
  run:
    working-directory: ./Azure-Managed-Service-Customer-Onboarding

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Validate -var 'customer_tenant_id=${{ github.event.inputs.CustomerTenantId }}'
        run: terraform validate

      - name: Terraform Plan -var 'customer_tenant_id=${{ github.event.inputs.CustomerTenantId }}'
        run: terraform plan
        
      # - name: Terraform Apply
      #   run: terraform apply --auto-approve
