name: Write File to Repo

on: 
  workflow_dispatch:
    inputs:
      customertenantid:
        description: 'Please provide the customer Azure AD tenant initial default domain. This will be the unique onmicrosoft.com domain name'
        required: true
        type: string
defaults:
  run:
    working-directory: ./Customer-Information

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: create file
        run: |
        echo "test" > test.txt

      - name: setup git config
        run: |
        git config user.name "GitHub Actions Bot"
        got config user.email "<>"

      - name: commit
        run: |
        git add test.txt
        got commit -m "add test file"
        git push origin master
jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2

      - name: save current date
        run: |
          # do some operation that changes a file in the git repo
          date > time.txt

      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: commit
        run: |
          # Stage the file, commit and push
          git add time.txt
          git commit -m "new date commit"
          git push origin master