name: Write File to Repo

on: 
  workflow_dispatch:
    inputs:
      customertenantid:
        description: 'Please provide the customer Azure AD tenant initial default domain. This will be the unique onmicrosoft.com domain name'
        required: true
        type: string
defaults:
  run:
    working-directory: ./Customer-Information

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: create file
        run: |
          echo -n -e "test" > test.txt

      # - name: setup git config
      #   run: |
      #   git config user.name "kevinbasoftcat"
      #   git config user.email "<>"

      - name: commit
        run: |
        git add test.txt
        git commit -m "add test file"
        git push origin master